uploads = []
generated = []

[[outputs]]
id = "ynQYXTmgqxRBIleLfXulJ"
uri = "file://exports/shadownet-source.tar.gz"
type = "unspecified"
title = "ShadowNet Source (with latest fixes)"

[[outputs]]
id = "996YIrvEpX-DM0dlZ9sMp"
uri = "file://exports/shadownet-session-changes.tar.gz"
type = "unspecified"
title = "ShadowNet — Session Changes Only (58 KB)"
