import { useState } from "react";
import { useGenerateWallet, type GeneratedWallet } from "@/lib/wallet";
import { Key, Eye, EyeOff, Copy, Check, AlertTriangle, ShieldCheck, Cpu, Lock, Wifi } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

function CopyField({ label, value, hidden = false }: { label: string; value: string; hidden?: boolean }) {
  const [show, setShow] = useState(false);
  const [copied, setCopied] = useState(false);
  const copy = () => { navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between text-[10px] font-mono text-white/30 uppercase tracking-widest">
        <span>{label}</span>
        <div className="flex items-center gap-3">
          {hidden && (
            <button onClick={() => setShow(!show)} className="flex items-center gap-1 hover:text-white transition-colors">
              {show ? <EyeOff className="w-3 h-3" /> : <Eye className="w-3 h-3" />}
              {show ? "HIDE" : "REVEAL"}
            </button>
          )}
          <button onClick={copy} className="flex items-center gap-1 hover:text-primary transition-colors">
            {copied ? <Check className="w-3 h-3 text-primary" /> : <Copy className="w-3 h-3" />}
            {copied ? "COPIED" : "COPY"}
          </button>
        </div>
      </div>
      <div className="p-3.5 rounded-lg border border-white/8 bg-black font-mono text-xs text-white/70 break-all min-h-[44px] flex items-center">
        {hidden && !show ? <span className="tracking-[0.2em] text-white/25">{value.replace(/./g, "•")}</span> : <span>{value}</span>}
      </div>
    </div>
  );
}

export default function AppWallet() {
  const { mutate: generateWallet, isPending, error } = useGenerateWallet();
  const [wallets, setWallets] = useState<GeneratedWallet[]>([]);
  const current = wallets[0];
  const history = wallets.slice(1);

  const handleGenerate = () => {
    generateWallet(undefined, {
      onSuccess: data => {
        setWallets(p => [data, ...p].slice(0, 4));
        try { localStorage.setItem("sn_wallets", String((parseInt(localStorage.getItem("sn_wallets") ?? "0", 10)) + 1)); } catch {}
      }
    });
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-mono font-bold text-white mb-1">Wallet Generator</h1>
        <p className="text-xs font-mono text-white/35">Burner Solana keypairs, generated locally in your browser. Zero network egress for keys.</p>
      </div>

      {/* Honest, upfront security notice */}
      <div className="p-5 rounded-xl border border-amber-500/25 bg-amber-500/[0.04] space-y-3">
        <div className="flex gap-3 items-start">
          <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
          <div className="space-y-2">
            <p className="text-xs font-mono font-bold text-white">FOR DISPOSABLE / BURNER WALLETS ONLY</p>
            <ul className="text-[11px] font-mono text-white/55 leading-relaxed space-y-1 list-disc pl-4">
              <li>Use these keys for one-off mints, airdrop hunting, or testnet activity.</li>
              <li>For meaningful funds use a hardware wallet (Ledger, Trezor) — any browser-resident key, including those generated by Phantom or Solflare, is exposed if your machine or browser is compromised.</li>
              <li>Never paste your private key or seed phrase into any website that didn't generate it.</li>
            </ul>
          </div>
        </div>
        <button onClick={handleGenerate} disabled={isPending}
          className="w-full px-5 py-3 bg-purple-500 text-white font-mono font-bold text-xs rounded-lg hover:bg-purple-400 transition-colors disabled:opacity-50 tracking-widest"
          style={{ boxShadow: "0 0 20px rgba(139,92,246,0.25)" }}>
          {isPending ? "COMPUTING…" : "GENERATE BURNER KEYPAIR"}
        </button>
        {error && (
          <div className="p-3 rounded-lg border border-red-500/30 bg-red-500/5">
            <p className="text-[11px] font-mono text-red-400">{error.message}</p>
          </div>
        )}
      </div>

      <AnimatePresence mode="popLayout">
        {current ? (
          <motion.div key={current.publicKey} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
            className="p-6 rounded-xl border border-white/8 bg-white/[0.02] space-y-5">
            <div className="flex items-center justify-between border-b border-white/6 pb-4">
              <div className="flex items-center gap-2 text-xs font-mono font-bold text-white">
                <Key className="w-4 h-4 text-purple-400" />
                Active Keypair
              </div>
              <span className="text-[10px] font-mono text-purple-400 border border-purple-500/25 px-2 py-1 rounded bg-purple-500/8">ED25519_BASE58</span>
            </div>
            <CopyField label="Public Key (Address)" value={current.publicKey} />
            <CopyField label="Private Key" value={current.privateKey} hidden />
            <CopyField label="Mnemonic Seed Phrase" value={current.mnemonic} hidden />
            <div className="flex flex-wrap gap-4 text-[10px] font-mono text-white/25 border-t border-white/6 pt-4">
              <span>PATH: <span className="text-white/50">{current.derivationPath}</span></span>
              <span>GENERATED: <span className="text-white/50">{new Date(current.createdAt).toISOString()}</span></span>
            </div>
          </motion.div>
        ) : (
          <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="py-20 flex flex-col items-center justify-center border border-dashed border-white/8 rounded-xl">
            <Key className="w-8 h-8 text-white/15 mb-3" />
            <p className="text-xs font-mono text-white/25">No keys generated in current session.</p>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Generation transparency — auditable proof of how this key was made */}
      {current && (
        <div className="p-5 rounded-xl border border-primary/20 bg-primary/[0.03] space-y-4">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-3.5 h-3.5 text-primary" />
            <p className="text-[10px] font-mono text-primary uppercase tracking-widest">Generation Transparency</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="flex items-start gap-2.5 p-3 rounded-lg bg-black/40 border border-white/5">
              <Wifi className="w-3.5 h-3.5 text-primary/70 shrink-0 mt-0.5" />
              <div>
                <p className="text-[10px] font-mono text-white/40 uppercase tracking-wider">Where</p>
                <p className="text-xs font-mono text-white">100% client-side — no network egress for keys</p>
              </div>
            </div>
            <div className="flex items-start gap-2.5 p-3 rounded-lg bg-black/40 border border-white/5">
              <Cpu className="w-3.5 h-3.5 text-primary/70 shrink-0 mt-0.5" />
              <div>
                <p className="text-[10px] font-mono text-white/40 uppercase tracking-wider">Entropy</p>
                <p className="text-xs font-mono text-white">{current.provenance.entropySource} ({current.provenance.rngBits}-bit, OS RNG)</p>
              </div>
            </div>
            <div className="flex items-start gap-2.5 p-3 rounded-lg bg-black/40 border border-white/5">
              <Lock className="w-3.5 h-3.5 text-primary/70 shrink-0 mt-0.5" />
              <div>
                <p className="text-[10px] font-mono text-white/40 uppercase tracking-wider">Standards</p>
                <p className="text-xs font-mono text-white">{current.provenance.mnemonicStandard} → {current.provenance.derivationStandard} ({current.provenance.curve})</p>
              </div>
            </div>
            <div className="flex items-start gap-2.5 p-3 rounded-lg bg-black/40 border border-white/5">
              <ShieldCheck className="w-3.5 h-3.5 text-primary/70 shrink-0 mt-0.5" />
              <div>
                <p className="text-[10px] font-mono text-white/40 uppercase tracking-wider">Context</p>
                <p className="text-xs font-mono text-white">
                  {current.provenance.secureContext ? "Secure context (HTTPS / localhost)" : "Insecure context — keys not generated"}
                </p>
              </div>
            </div>
          </div>
          <div className="pt-2 border-t border-white/5">
            <p className="text-[10px] font-mono text-white/40 uppercase tracking-wider mb-1.5">Audited libraries used</p>
            <div className="flex flex-wrap gap-1.5">
              {current.provenance.libraries.map(lib => (
                <span key={lib} className="text-[10px] font-mono px-2 py-1 rounded border border-primary/20 text-primary/80 bg-primary/5">
                  {lib}
                </span>
              ))}
            </div>
            <p className="text-[10px] font-mono text-white/30 mt-2 leading-relaxed">
              Sensitive intermediate buffers (BIP-39 seed, HMAC outputs, derived chain code, secret-key array) are zero-filled in memory on a best-effort basis after encoding. The mnemonic and private-key strings remain in this React tree until you reload — JavaScript strings are immutable and cannot be wiped.
            </p>
          </div>
        </div>
      )}

      {/* Import instructions */}
      {current && (
        <div className="p-5 rounded-xl border border-white/6 bg-black/40 space-y-3">
          <p className="text-[10px] font-mono text-primary/70 uppercase tracking-widest">How to import into Phantom</p>
          {["Open Phantom browser extension","Click avatar → Add/Connect Wallet → Import Private Key","Paste the Base58 Private Key revealed above","Click Import — done."].map((step, i) => (
            <div key={i} className="flex gap-3 text-xs font-mono text-white/40">
              <span className="text-primary/50 shrink-0">{i+1}.</span>
              <span>{step}</span>
            </div>
          ))}
        </div>
      )}

      {history.length > 0 && (
        <div>
          <p className="text-[10px] font-mono text-white/20 uppercase tracking-widest mb-3">Session History</p>
          <div className="space-y-2">
            {history.map((w, i) => (
              <div key={i} className="flex items-center justify-between p-3 border border-white/6 rounded-lg text-[10px] font-mono">
                <span className="text-white/30">{w.publicKey.slice(0,20)}…</span>
                <span className="text-white/20">{new Date(w.createdAt).toLocaleTimeString()}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
